version: '3'

services:
  db:
    image: postgres
    container_name: pywishdb
  web:
    build: .
    container_name: pywishapp
    ports:
      - "8991:8000"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - nginx_network
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: pywishgtw
    ports:
      - 8992:80
    depends_on:
      - web
    networks: 
      - nginx_network

networks:
  nginx_network:
    driver: bridge