version: '3'

services:
  db:
    image: postgres
    container_name: pywishdb
  web:
    build: .
    container_name: pywishapp
    ports:
      - "8991:8000"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
