version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 pywishproject/manage.py runserver 0.0.0.0:8990
    ports:
      - "8990:8990"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db