# Generated by Django 2.2.5 on 2019-09-30 22:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('crated_on', models.DateField(auto_now_add=True)),
                ('crated_by', models.CharField(max_length=250)),
                ('updated_on', models.DateField()),
                ('updated_by', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
