# Generated by Django 2.2.5 on 2019-09-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='updated_by',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
