# Generated by Django 2.2.5 on 2019-09-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20190930_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
