# Generated by Django 2.2.5 on 2019-09-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20190930_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
