# Generated by Django 2.2.5 on 2019-09-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_auto_20190930_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='crated_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='crated_on',
            new_name='created_on',
        ),
    ]
